# sonar-project.properties
sonar.projectKey=amd-khalid
sonar.organization=amd-khalid

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Vulnerable Corp App
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.
sonar.language=py
sonar.python.version=3.9

# Exclude files from being scanned (like the SBOM report if it's in the directory)
sonar.exclusions=**/requirements.txt, **/*.html
sonar.python.coverage.reportPaths=coverage.xml